const metaPlans = [
  { name: "Launch", price: "$149", cadence: "one-time", description: "A focused campaign setup for your first confident step into paid growth.", features: ["Account & pixel audit", "Campaign architecture", "Creative direction", "30-day launch map"] },
  { name: "Growth", price: "$299", cadence: "per month", description: "A steady performance engine for teams ready to turn attention into action.", features: ["Everything in Launch", "Weekly optimization", "Audience testing", "Monthly performance report"], featured: true },
  { name: "Scale", price: "$499", cadence: "per month", description: "Full-funnel momentum with the strategy and rigor to compound results.", features: ["Everything in Growth", "Multi-channel retargeting", "Creative testing system", "Priority strategy calls"] },
];
const aiPlans = [
  { name: "Basic", price: "$29", description: "One sharp AI assistant for the questions your customers ask most.", tag: "1 agent" },
  { name: "Pro", price: "$79", description: "A smarter support layer that qualifies, routes, and converts around the clock.", tag: "3 agents", featured: true },
  { name: "Elite", price: "$149", description: "A custom AI team trained on your business, brand voice, and workflows.", tag: "Unlimited agents" },
];
function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return <main>
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><a href="#top" className="flex items-center gap-3 text-sm font-bold tracking-[.18em] text-white"><span className="flex h-8 w-8 items-center justify-center bg-[#2F8DF5] text-sm font-black">LS</span> LINCSCALES</a><div className="hidden items-center gap-8 text-sm text-slate-400 md:flex"><a href="#services" className="hover:text-white">Services</a><a href="/packages" className="hover:text-white">Packages</a><a href="#ai" className="hover:text-white">AI marketplace</a><a href="/onboarding" className="hover:text-white">Client login</a></div><a href="/request" className="button-outline px-4 py-2 text-xs font-semibold">Start a project <Arrow /></a></nav>
    <section id="top" className="grid-lines relative overflow-hidden border-y border-white/10"><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-32"><div><p className="eyebrow mb-7">Performance marketing · AI automation</p><h1 className="max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white sm:text-7xl">Your business.<br /><span className="text-[#2F8DF5]">Scaled.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-400">LincScales pairs high-intent advertising with practical AI systems, so your next stage of growth feels less like a gamble and more like a plan.</p><div className="mt-10 flex flex-wrap gap-3"><a href="/request" className="button-blue px-6 py-3 text-sm font-bold">Build my growth plan <Arrow /></a><a href="#services" className="button-outline px-6 py-3 text-sm font-semibold">See how we work</a></div><div className="mt-16 flex gap-10 text-xs text-slate-500"><span><strong className="block text-2xl font-semibold text-white">04</strong>growth levers</span><span><strong className="block text-2xl font-semibold text-white">24/7</strong>AI coverage</span><span><strong className="block text-2xl font-semibold text-white">1:1</strong>strategy</span></div></div><div className="relative mx-auto w-full max-w-md"><div className="blue-glow absolute -inset-8 rounded-full bg-[#2F8DF5]/10 blur-3xl" /><div className="card relative p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4 text-xs text-slate-400"><span>LINCSCALES / CONTROL ROOM</span><span className="flex items-center gap-2 text-[#74b7ff]"><i className="h-2 w-2 rounded-full bg-[#2F8DF5]" /> Live system</span></div><div className="py-10"><div className="mb-2 text-xs text-slate-500">Pipeline velocity</div><div className="flex items-end gap-3"><span className="text-5xl font-semibold tracking-[-.05em] text-white">+68.4%</span><span className="mb-2 text-xs text-[#62adff]">vs. last cycle</span></div><div className="mt-8 flex h-32 items-end gap-2">{[32,42,38,57,64,76,100].map((height) => <span key={height} className="flex-1 bg-[#2F8DF5]" style={{ height: `${height}%`, opacity: height / 110 }} />)}</div></div><div className="grid grid-cols-2 gap-3"><div className="border border-white/10 p-3"><div className="text-xs text-slate-500">Qualified leads</div><div className="mt-2 text-xl font-semibold text-white">1,284</div></div><div className="border border-white/10 p-3"><div className="text-xs text-slate-500">ROAS</div><div className="mt-2 text-xl font-semibold text-white">4.8x</div></div></div></div></div></div></section>
    <section id="services" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12 max-w-2xl"><p className="eyebrow mb-4">One partner, two growth engines</p><h2 className="text-4xl font-semibold tracking-[-.04em] text-white sm:text-5xl">Make your marketing work harder.</h2></div><div className="grid gap-4 md:grid-cols-2"><a href="#pricing" className="card card-hover group p-8"><span className="text-3xl text-[#2F8DF5]">01</span><h3 className="mt-16 text-2xl font-semibold text-white">Meta Ads that move the needle <span className="text-[#2F8DF5] opacity-0 transition-opacity group-hover:opacity-100"><Arrow /></span></h3><p className="mt-4 max-w-md leading-7 text-slate-400">From first campaign to full-funnel scale, we find the audience, message, and offer combination that earns attention.</p><span className="mt-8 inline-block text-sm font-semibold text-[#74b7ff]">Explore packages <Arrow /></span></a><a href="#ai" className="card card-hover group p-8"><span className="text-3xl text-[#2F8DF5]">02</span><h3 className="mt-16 text-2xl font-semibold text-white">AI that works while you sleep <span className="text-[#2F8DF5] opacity-0 transition-opacity group-hover:opacity-100"><Arrow /></span></h3><p className="mt-4 max-w-md leading-7 text-slate-400">Deploy a trained assistant for support, sales, or operations without adding another tab to your team’s day.</p><span className="mt-8 inline-block text-sm font-semibold text-[#74b7ff]">Browse the marketplace <Arrow /></span></a></div></section>
    <section id="pricing" className="section-rule mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow mb-4">Meta Ads packages</p><h2 className="text-4xl font-semibold tracking-[-.04em] text-white">A clear place to start.</h2></div><a href="/request" className="text-sm font-semibold text-[#74b7ff]">Need something custom? <Arrow /></a></div><div className="grid gap-4 lg:grid-cols-3">{metaPlans.map((plan) => <div key={plan.name} className={`card card-hover relative flex flex-col p-7 ${plan.featured ? "border-[#2F8DF5]/70 blue-glow" : ""}`}>{plan.featured && <span className="absolute right-5 top-5 bg-[#2F8DF5] px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Most popular</span>}<p className="eyebrow">{plan.name}</p><div className="mt-7 flex items-baseline gap-2"><span className="text-5xl font-semibold tracking-[-.06em] text-white">{plan.price}</span><span className="text-sm text-slate-500">{plan.cadence}</span></div><p className="mt-5 min-h-20 leading-7 text-slate-400">{plan.description}</p><div className="my-6 border-t border-white/10" />{plan.features.map((feature) => <div key={feature} className="mb-3 flex gap-3 text-sm text-slate-300"><span className="text-[#2F8DF5]">+</span>{feature}</div>)}<a href="/request" className={`mt-8 w-full py-3 text-center text-sm font-bold ${plan.featured ? "button-blue" : "button-outline"}`}>Choose {plan.name}</a></div>)}</div></section>
    <section id="ai" className="section-rule bg-[#07101c] py-24"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="mb-12 max-w-2xl"><p className="eyebrow mb-4">AI chatbot marketplace</p><h2 className="text-4xl font-semibold tracking-[-.04em] text-white sm:text-5xl">Give your best people<br />more time to think.</h2><p className="mt-5 leading-7 text-slate-400">Pick a starting point. Make it yours. Every plan includes a guided setup and a workspace to keep improving your assistant.</p></div><div className="grid gap-4 lg:grid-cols-3">{aiPlans.map((plan) => <div key={plan.name} className={`card card-hover p-7 ${plan.featured ? "border-[#2F8DF5]/70" : ""}`}><div className="flex justify-between"><p className="eyebrow">{plan.name}</p><span className="text-xs text-slate-500">{plan.tag}</span></div><div className="mt-7 text-4xl font-semibold tracking-[-.05em] text-white">{plan.price}<span className="ml-2 text-sm font-normal tracking-normal text-slate-500">/ month</span></div><p className="mt-5 min-h-20 leading-7 text-slate-400">{plan.description}</p><a href="/platform" className="mt-7 block border-t border-white/10 pt-5 text-sm font-semibold text-[#74b7ff]">View assistant details <Arrow /></a></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="relative overflow-hidden border border-[#2F8DF5]/40 bg-[#0c2037] p-8 sm:p-12"><div className="relative max-w-2xl"><p className="eyebrow mb-4">The next move is yours</p><h2 className="text-4xl font-semibold tracking-[-.04em] text-white">Stop guessing what growth could look like.</h2><p className="mt-5 leading-7 text-slate-300">Tell us where you are and where you want to go. We’ll send back a practical plan, not a sales script.</p><a href="/request" className="button-blue mt-8 inline-block px-6 py-3 text-sm font-bold">Request a custom plan <Arrow /></a></div></div></section>
    <footer className="section-rule mx-auto flex max-w-7xl flex-col gap-5 px-6 py-8 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-10"><span className="font-bold tracking-[.18em] text-slate-300">LINCSCALES</span><span>Your Business. Scaled. © 2026</span><span className="flex gap-5"><a href="/admin" className="hover:text-white">Admin</a><a href="/platform" className="hover:text-white">Platform</a></span></footer>
  </main>;
}